version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/0x6f736f646f/memfault-go"
  dependencies_vendored = true

[[transformers]]
name = "gofmt"
enabled = true